-<!DOCTYPE html>
-<html>
-	<head>
-		<meta name="layout" content="main">
-	</head>
-	<body>
-		<h1>Se ha creado la rifa correctamente</h1>
-		<g:link controller="raffle" action="show">Show</g:link>
-	</body>
-</html>